let token=localStorage.getItem('playpulse-token')||'';
let username=localStorage.getItem('playpulse-user')||'';
let authMode='login';
const page=document.documentElement.dataset.page;
const $=id=>document.getElementById(id);
const escapeHTML=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const formatDate=value=>{if(!value)return'Just now';const date=new Date(value);return Number.isNaN(date.valueOf())?'Just now':date.toLocaleDateString(undefined,{month:'short',day:'numeric'});};
const api=async(path,options={})=>{const headers={...(options.headers||{}),...(token?{Authorization:'Bearer '+token}:{})};if(options.body)headers['Content-Type']='application/json';const response=await fetch('/api/'+path,{...options,headers});let payload={};try{payload=await response.json()}catch{}if(!response.ok||payload.code!==200)throw new Error(payload.message||'The service could not complete that request.');return payload.data;};
function setMessage(id,text='',error=false){const element=$(id);if(!element)return;element.textContent=text;element.classList.toggle('error',error);}
function syncSession(){const name=$('session-name'),link=$('account-link'),button=$('signout');if(name)name.textContent=token?`Signed in as ${username||'player'}`:'Guest session';if(link)link.hidden=!!token;if(button)button.hidden=!token;const accountForms=$('account-forms'),signed=$('account-signed-in');if(accountForms&&signed){accountForms.hidden=!!token;signed.hidden=!token;if(token){$('account-user').textContent=`Signed in as ${username||'player'}`;loadMySignals();}else if($('my-signals'))$('my-signals').innerHTML='';}if(page==='submit')setMessage('submit-message',token?'Your name is attached to every signal.':'Sign in before publishing a signal.');}
function signOut(){localStorage.removeItem('playpulse-token');localStorage.removeItem('playpulse-user');token='';username='';syncSession();}
async function loadDashboard(){try{const data=await api('feedback/dashboard');for(const [id,value] of Object.entries({'metric-total':data.total,'metric-reported':data.reported,'metric-progress':data.inProgress,'metric-fixed':data.fixed})){const target=$(id);if(target)target.textContent=value??0;}}catch{['metric-total','metric-reported','metric-progress','metric-fixed'].forEach(id=>{if($(id))$(id).textContent='--';});}}
function mySignalCard(item){return `<article class="report"><div class="report-top"><h3>${escapeHTML(item.title)}</h3><span class="status">${escapeHTML(String(item.status||'REPORTED').replace('_',' '))}</span></div><div class="report-meta"><b>${escapeHTML(item.category)}</b><span class="meta-dot"></span><span>${Number(item.voteCount||0)} vote${Number(item.voteCount||0)===1?'':'s'}</span><span class="meta-dot"></span><span>${Number(item.commentCount||0)} comment${Number(item.commentCount||0)===1?'':'s'}</span></div></article>`;}
async function loadMySignals(){const list=$('my-signals');if(!list||!token)return;list.innerHTML='<div class="skeleton"><i></i><i></i></div>';try{const result=await api('feedback/mine?size=10'),rows=result.content||[];list.innerHTML=rows.length?rows.map(mySignalCard).join(''):'<div class="empty">No signals from you yet.</div>';}catch(error){list.innerHTML=`<p class="form-message error">${escapeHTML(error.message)}</p>`;}}
function reportCard(item){const id=Number(item.id),votes=Number(item.voteCount||0),comments=Number(item.commentCount||0);return `<article class="report"><div class="report-top"><h3>${escapeHTML(item.title)}</h3><span class="status">${escapeHTML(String(item.status||'REPORTED').replace('_',' '))}</span></div><p>${escapeHTML(item.description)}</p><div class="report-meta"><b>${escapeHTML(item.category)}</b><span class="meta-dot"></span><span>${escapeHTML(item.priority)} impact</span><span class="meta-dot"></span><span>${formatDate(item.createdAt)}</span><button class="vote" type="button" onclick="vote(${id})" aria-label="Vote for ${escapeHTML(item.title)}">↑ ${votes} vote${votes===1?'':'s'}</button><button class="discussion-toggle" type="button" onclick="toggleDiscussion(${id})">Discuss ${comments}</button></div><div class="discussion" id="discussion-${id}"></div></article>`;}
async function loadFeedback(){const list=$('feed-list');if(!list)return;list.innerHTML='<div class="skeleton"><i></i><i></i><i></i></div>';try{const query=new URLSearchParams({search:$('search').value.trim(),sort:$('sort').value,size:'30'});if($('category-filter').value)query.set('category',$('category-filter').value);const result=await api('feedback?'+query.toString()),rows=result.content||[];$('result-count').textContent=`${result.totalElements||0} signal${(result.totalElements||0)===1?'':'s'}`;list.innerHTML=rows.length?rows.map(reportCard).join(''):'<div class="empty">No signals match this view.<br>Try another filter or publish the first report.</div>';}catch(error){$('result-count').textContent='Offline';list.innerHTML=`<div class="empty">Connection failed.<br>${escapeHTML(error.message)}</div>`;}}
async function submitFeedback(event){event.preventDefault();if(!token){window.location.href='account.html';return;}const title=$('title').value.trim(),description=$('description').value.trim();if(!title||!description){setMessage('submit-message','Add a title and useful context before publishing.',true);return;}try{await api('feedback',{method:'POST',body:JSON.stringify({title,description,category:$('category').value,priority:$('priority').value})});event.target.reset();setMessage('submit-message','Signal published. It is now waiting for triage.');loadDashboard();}catch(error){setMessage('submit-message',error.message,true);}}
async function vote(id){if(!token){window.location.href='account.html';return;}try{await api(`feedback/${id}/votes`,{method:'POST'});loadFeedback();}catch(error){const list=$('feed-list');if(list)list.insertAdjacentHTML('afterbegin',`<p class="form-message error">${escapeHTML(error.message)}</p>`);}}
async function toggleDiscussion(id){const box=$(`discussion-${id}`);if(box.classList.contains('open')){box.classList.remove('open');return;}box.classList.add('open');box.innerHTML='<div class="comment">Loading discussion…</div>';try{const comments=await api(`feedback/${id}/comments`);const entries=comments.length?comments.map(comment=>`<div class="comment">${escapeHTML(comment.content)}<small>Player ${escapeHTML(comment.userId)} · ${formatDate(comment.createdAt)}</small></div>`).join(''):'<div class="comment">No replies yet. Start a useful discussion.</div>';box.innerHTML=entries+(token?`<form class="comment-form" onsubmit="postComment(event,${id})"><input required maxlength="1000" aria-label="Add a comment" placeholder="Add context or a workaround"><button class="button" type="submit">Reply</button></form>`:'<div class="comment"><small>Sign in to add a reply.</small></div>');}catch(error){box.innerHTML=`<div class="comment">Could not load discussion. ${escapeHTML(error.message)}</div>`;}}
async function postComment(event,id){event.preventDefault();const input=event.currentTarget.querySelector('input'),content=input.value.trim();if(!content)return;try{await api(`feedback/${id}/comments`,{method:'POST',body:JSON.stringify({content})});const box=$(`discussion-${id}`);box.classList.remove('open');await toggleDiscussion(id);}catch(error){input.setCustomValidity(error.message);input.reportValidity();}}
function setAuthMode(mode){authMode=mode;$('login-tab').classList.toggle('active',mode==='login');$('register-tab').classList.toggle('active',mode==='register');$('auth-submit').textContent=mode==='login'?'Sign in':'Create account';setMessage('auth-message');}
async function handleAuth(event){event.preventDefault();const user=$('auth-username').value.trim(),password=$('auth-password').value;if(user.length<3||password.length<4){setMessage('auth-message','Use at least 3 characters for your username and 4 for your password.',true);return;}try{const data=await api('auth/'+authMode,{method:'POST',body:JSON.stringify({username:user,password})});if(authMode==='register'){setMessage('auth-message','Account created. You can sign in now.');setAuthMode('login');return;}token=data.token;username=data.username||user;localStorage.setItem('playpulse-token',token);localStorage.setItem('playpulse-user',username);syncSession();}catch(error){setMessage('auth-message',error.message,true);}}
window.vote=vote;window.toggleDiscussion=toggleDiscussion;window.postComment=postComment;
if($('signout'))$('signout').addEventListener('click',signOut);if($('account-signout'))$('account-signout').addEventListener('click',signOut);if(page==='overview')loadDashboard();if(page==='board'){$('apply-filter').addEventListener('click',loadFeedback);$('search').addEventListener('keydown',event=>{if(event.key==='Enter')loadFeedback();});loadFeedback();}if(page==='submit')$('feedback-form').addEventListener('submit',submitFeedback);if(page==='account'){$('login-tab').addEventListener('click',()=>setAuthMode('login'));$('register-tab').addEventListener('click',()=>setAuthMode('register'));$('auth-form').addEventListener('submit',handleAuth);}syncSession();
